- hosts: swarm_master
  tasks:
    - name: Running the Service
      docker_swarm_service:
        image: fx8350:5000/website:latest
        name: website
        state: present
        resolve_image: yes
        publish:
          - mode: ingress
            published_port: 5000
            target_port: 5000
        replicas: 3
        hostname: "{{ ansible_hostname }}"
